"""Single source of truth for the docket set, read from data/case-meta.yaml.

All the data scripts import DOCKET_IDS and the level helpers from here instead
of hardcoding court keys, so the toolkit is docket-agnostic: a new case is a
case-meta.yaml edit, nothing else. The TS/build side reads the same YAML via
lib/dockets.config.ts (generated by scripts/gen-dockets-config.mjs).

Sibling import: the scripts run as `python3 scripts/<name>.py`, which puts this
directory on sys.path, so `from case_config import DOCKET_IDS` resolves.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip3 install pyyaml", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parent.parent
CASE_META = ROOT / "data" / "case-meta.yaml"

# HTTP User-Agent for CourtListener requests; override per deployment via the
# MONITOR_USER_AGENT env var.
USER_AGENT = os.environ.get("MONITOR_USER_AGENT") or "docket-tracker"


def load_dockets() -> list[dict]:
    """The `dockets:` list from case-meta.yaml (empty when absent)."""
    meta = yaml.safe_load(CASE_META.read_text(encoding="utf-8")) or {}
    return meta.get("dockets") or []


DOCKETS: list[dict] = load_dockets()

# id -> CourtListener docket id (only dockets that declare one).
DOCKET_IDS: dict[str, int] = {
    d["id"]: d["courtlistener_id"]
    for d in DOCKETS
    if d.get("id") and d.get("courtlistener_id")
}

# id -> 'trial' | 'appellate' (defaults to 'trial' when unspecified).
LEVELS: dict[str, str] = {
    d["id"]: ("appellate" if d.get("level") == "appellate" else "trial")
    for d in DOCKETS
    if d.get("id")
}


def is_trial(court: str) -> bool:
    """Trial courts dedup/key by entry_number; appellate courts don't."""
    return LEVELS.get(court, "trial") == "trial"


def is_appellate(court: str) -> bool:
    return LEVELS.get(court) == "appellate"
